# Generated by Django 5.0.6 on 2024-06-01 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='StudendId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=100)),
                ('studentage', models.CharField(max_length=100)),
                ('studentemail', models.EmailField(max_length=100)),
                ('studentaddress', models.TextField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='myapp.department')),
                ('studendid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studenttidd', to='myapp.studendid')),
            ],
            options={
                'verbose_name': 'student',
                'ordering': ['studentname'],
            },
        ),
    ]
