# Generated by Django 4.2.2 on 2024-06-03 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studendid',
            old_name='studentid',
            new_name='student_id',
        ),
    ]
